### ISSUE TITLE
Not compatible with WP 5.6

### ISSUE THREAD

**Issue by nick6352683** [tmconnect/ACF-Justified-Image-Grid#11]
The swipebox fails with WP 5.6, and advice how to fix this please?

**Comment by sixtyseven-multimedia** [comment]
Same problem here. The used swipebox is https://github.com/brutaldesign/swipebox which was last updated 5 years ago. Would be great if we get a asolution, because this field is a really valuable addon to ACF!

**Comment by Monti213** [comment]
same problem(

**Comment by ellenbo** [comment]
I am also seeing the same problem. We've downgraded our WP version for now but are hoping this will be resolved soon. Thanks!

**Comment by nick6352683** [comment]
Downgrading WP is a solution but not an ideal one - and don't let others fool you - downgrading is not a security issue, as older WP version also get security updates (I think downgrading all the way to WP 4.0 you should be fine, but check on this with the core team on Slack)... That said, with a WP downgrade you might miss out of some nice new features...

What I did was I installed https://wordpress.org/plugins/version-control-for-jquery/ and downgraded the JQuery library to the latest version that all my plugins rely on to the earlier JQuery versions, and have not been updated, just for these plugins to continue working.

Finally, after this, I will be thinking very hard in the future to use any plugin that uses JQuery.

**Comment by tmconnect** [comment]
Please try the new version which includes a new SwipeBox for jQuery 3.5+

**Comment by nick6352683** [comment]
@tmconnect : I just saw the update - thanks a million, I will be testing it over the weekend - BTW - You freaking rock !!!

**Comment by nick6352683** [comment]
After testing, I can verify that the new update fixes the issue.

Once again, thanks a million Thomas.
