### ISSUE TITLE
Using multiple justified fields within a group causes error

### ISSUE THREAD

**Issue by andielliott** [tmconnect/ACF-Justified-Image-Grid#2]
Creating multiple entries in a field group causes the following error:

Fatal error: Cannot redeclare cmp() (previously declared in /public_html/wp-content/plugins/ACF-Justified-Image-Grid-master/acf-justified-image-grid-v5.php:966) in /public_html/wp-content/plugins/ACF-Justified-Image-Grid-master/acf-justified-image-grid-v5.php on line 966

**Comment by tmconnect** [comment]
Thanks for your info and your pull request.

I just pushed a new version to make this work. It needs a little more than your pull request, because the Swipebox  functionality needs to be changed, too.
