### ISSUE TITLE
Not working with WP 4.5.2 and ACF Pro 5.3.8.1

### ISSUE THREAD

**Issue by davemac** [tmconnect/ACF-Justified-Image-Grid#5]
Hi there,

I have created a gallery inside a repeater field, however when I click add gallery and select the images the gallery is empty in the post edit screen.

The JS error is:

`Uncaught TypeError: Cannot read property 'url' of undefined on /wp-content/plugins/acf-justified-image-grid/js/input.js line 845`

**Comment by tmconnect** [comment]
I tested with WP 4.5.2 and ACF 5.3.8.1 and it worked as it should without any errors.

Please send a screenshot with your current settings or prepare an ACF export file for testing.

Cheers
Thomas

**Comment by sixtyseven-multimedia** [comment]
Works like a charm with the actual WP/ACF. Would like to see a setting if the title should be present in the swipe box, others than that: This one is a real gem.

**Comment by sixtyseven-multimedia** [comment]
How about this way? (function format_value())

`if ( $swipebox == 'yes' ) {
								echo '<a class="swipebox" data-rel="gallery' . $field['ID'] . '" href="' . $image["url"] . '"';
								if ( $show_captions == 'true' ) {
									echo ' data-title="' . esc_attr($image["title"]) . '"';
								}
								echo '></a>';
							}`

**Comment by davemac** [comment]
Tested on another site and all working fine with WP 4.6 and ACF Pro 5.4.2, so as you were ...
