### ISSUE TITLE
Justified grid not displaying

### ISSUE THREAD

**Issue by bitsavvy** [tmconnect/ACF-Justified-Image-Grid#6]
Hi there,

For some or other reason I cannot get the justified image grid to display.

When adding photo to the grid I get the following as per supplied screenshot → https://db.tt/ItUPJbhj4B

Screenshots of settings: https://db.tt/MsLzoB0XrX and https://db.tt/nxISGjpXBU

Would it be possible for to offer some suggestion of what I am doing wrong. Any help would be greatly appreciated.

Kind regards
Francois Wessels

**Comment by tmconnect** [comment]
As I see in your settings, there are no "Image Sizes" listed, what tells me, that you didn't have set any image sizes for the plugin.

You have to set one image size at least, with an unlimited width. To do this, set this image size within your functions.php. If your functions.php already defines some image sizes, add some sizes like this (the heights depending on your layout):

```
add_image_size( 'Small', 9999, 100, false);
add_image_size( 'Medium', 9999, 200, false);
add_image_size( 'Large', 9999, 300, false);
```

If no image sizes are already set, put the code in an action

```
add_action( 'after_setup_theme', 'my_new_images_sizes' );
function my_new_images_sizes() {
    add_image_size( 'Small', 9999, 100, false);
    add_image_size( 'Medium', 9999, 200, false);
    add_image_size( 'Large', 9999, 300, false);
}
```

Now you can select the sizes from the field settings and the gallery should be displayed.

Hope this helps.

**Comment by bitsavvy** [comment]
Thank you Thomas, that worked perfectly :)

Could I ask one more thing -- what CSS should I target to get the image grid to align better. PLease supplied screenshot: https://db.tt/bidOqy8h0M

Hope you can assist.

Kind regards
Francois Wessels

**Comment by tmconnect** [comment]
It's difficult to get an idea what causes the bad alignment by a screenshot. Is there a way that I could have a look on the site?

Cheers, Thomas

**Comment by bitsavvy** [comment]
Hi Thomas,

Thanks for your help. Is there a way that i can send a link via e-mail to you -- this is on my dev machine but I can let you have access via ngrok.

Kind regards
Francois
