### ISSUE TITLE
Image Sizes not visible

### ISSUE THREAD

**Issue by andiszek** [tmconnect/ACF-Justified-Image-Grid#7]
Hallo Thomas,
great Plugin, i love it!

I`ve stumbled upon an issue: the Image Sizes are not visible in the Grid Settings:
<img width="790" alt="screenshot 2017-09-28 20 54 42" src="https://user-images.githubusercontent.com/1119062/30982193-59a95a62-a48f-11e7-9fa9-63c7eb6f1bd8.png">

I'm using WP 4.8.2 and ACF 5.6.2
Unfortunately the big images are loading now instead of the Thumbnails and the page load is huge:(

I have also defined a 9999px wide image size:
add_image_size('grid_h_300', 9999, 336, true);

Could you please look into it?

Danke & liebe Grüße,
andi

**Comment by tmconnect** [comment]
Did you set image sizes that have a width of 9999px? Only these image sizes are listed.

**Comment by andiszek** [comment]
Ah, got it!
i've eliminated the hard crop and now the size is visible!
add_image_size('grid_h_300', 9999, 336);

Sorry about that, should have tested it before commenting here!

LG, andi

**Comment by tmconnect** [comment]
No problem...
